#!/bin/bash

VAR=''
SAVEFILE=/users/PZS0720/tdalesandro/prsnlsp/scripts/saved_edits.txt
getalias () {
	while IFS= read -r line; do
		if [[ "$line" == *"$1"* ]]; then
			VAR=$(cut -d= -f 2 <<< $line)
		fi
	done < $SAVEFILE
}

main () {
        if [ $1 == '-print' ]; then
		echo -----$SAVEFILE-----
		cat $SAVEFILE
		return
	fi
        if [ $1 == '-clear' ]; then
		cp /dev/null $SAVEFILE
		return
	fi
	if [ $1 == '-edit' ]; then
		vim $SAVEFILE
		return
	fi 

	getalias $1
	if [ $VAR ]; then
		vim $VAR
	else
		echo I have no idea what im doing
	fi	
}
main $1
unset VAR
unset SAVEFILE
