#!/bin/bash

# check for file save flag -s
ALIAS="$1"
FILEPATH=$(pwd)/$2
SAVEFILE=/users/PZS0720/tdalesandro/prsnlsp/scripts/saved_edits.txt
main() {
	if ! [ $1 ]; then
		echo need a parameter!
		return
	fi
	if [ $1 == '-print' ]; then
                echo -----$SAVEFILE-----
                cat $SAVEFILE
                return
        fi
        if [ $1 == '-clear' ]; then
                cp /dev/null $SAVEFILE
                return
        fi
        if [ $1 == '-edit' ]; then
                vim $SAVEFILE
                return
        fi

	#SAVE
	echo $ALIAS=$FILEPATH >> $SAVEFILE
	echo saved $ALIAS=$FILEPATH

}
main $1 $2
unset ALIAS
unset FILEPATH
unset SAVEFILE
