#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SAVEN=saved_edits.txt
SAVEFILE=$SCRIPT_DIR/save_files/$SAVEN

handleFlag() {
        if [ $1 == '-print' ]; then
                echo -----$SAVEFILE-----
                cat $SAVEFILE
        fi
        if [ $1 == '-clear' ]; then
                cp /dev/null $SAVEFILE
		echo cleared $SAVEFILE
        fi
        if [ $1 == '-edit' ]; then
                vim $SAVEFILE
        fi
	if [ $1 == '-s' ]; then
		addalias "$@"
        fi
}

addalias() {
	SAVELINE="$2=$(pwd)/$3"
	while IFS= read -r line; do
                if [[ "$line" == "$2="* ]]; then
			sed -i "s@.*$2.*@$SAVELINE@" $SAVEFILE
			echo replaced $line
			return
                fi
        done < $SAVEFILE	

	echo $SAVELINE >> $SAVEFILE
	echo saved $2=$3
	unset SAVELINE
}


getalias () {
        while IFS= read -r line; do
                if [[ "$line" == "$1="* ]]; then
                        VAR=$(cut -d= -f 2 <<< $line)
                fi
        done < $SAVEFILE
}

main() {
	if [[ "$1" == *"-"* ]]; then
		handleFlag "$@"
		return
	fi

	getalias $1
	if [ $VAR ]; then
		vim $VAR
		unset VAR
	else
		echo unknown edit string.
	fi
}
main "$@"
unset SAVEFILE
