#!/bin/bash

echo aliases being added

#custom command
alias salias='source salias'
alias edit='myedit'

#CD
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias cd..='cd ..'
alias l..='cd ..; ls'

#RANDOM
alias gh='history | grep'
alias grep='grep -n --color=auto'
alias printline="printf \"\n---------------------------\n\""
alias linecount='wc -l'
alias time="/usr/bin/time -v"

#LS
alias la='ls -la'
alias ll='ls -lA'
alias l.='ls -d .* --color=auto'
alias ls="ls -l --color=always"

#UNSORTED
alias jump="source jump"
alias set="setj"
alias diff="diff -y --suppress-common-lines"
alias rm="rm -rf"
alias cps="copystore"
alias ls="ls -lh --color=always"
