#!/bin/bash

echo PERSONAL BASH CONFIG RUNNING

FILE=${BASH_SOURCE[0]}
FILENAME=$(echo $FILE | sed -e 's@.*/@@g')

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
INSTALL_DIR=$(dirname $SCRIPT_DIR)

# bash scripts to set things up

source $SCRIPT_DIR/prompt_config
export PATH=$PATH:$INSTALL_DIR/scripts/

#Use for platform specific bash configuration
export PF=$SCRIPT_DIR/pf
if test -f "$PF"; then
	. $PF
fi

